### Example 1. 리스트에서 배열 만들기
원소를 0부터 15까지 순서대로 갖는 1차원 배열을 만드세요.

In [1]:
import numpy as np
import pandas as pd

In [2]:
####### PLEASE IMPLEMENT HERE ##########
arr = 

In [3]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Example 2. 배열 형태 바꾸기
위에서 만든 arr 배열을 4x4 배열로 바꿔보세요.

In [4]:
####### PLEASE IMPLEMENT HERE ##########
arr2 = 

In [5]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Example 3. 짝수 번째 원소 값 바꾸기
위에서 바꾼 arr 배열의 짝수 번째 원소(인덱스: 홀수)들을 -1로 바꿔보세요.
주의: 수동으로 인덱스별로 일일히 바꾸지 않는 방향으로 진행해보세요.

In [6]:
####### PLEASE IMPLEMENT HERE ##########
arr3 =


In [7]:
print(arr3)

[ 0 -1  4 -1  8 -1 12 -1]


### Example 4. 데이터프레임 다루기
Pandas를 활용하여 서울 지하철 1호선의 새벽 4~6시 이용정보 데이터프레임을 다뤄봅시다.

In [8]:
mydata = [['동대문', 901, 23, 11029, 1950],
          ['동묘앞', 214, 1, 2921, 933], 
          ['서울역', 665, 20, 7969, 7954],
          ['시청', 65, 0, 2188, 4984],
          ['신설동', 373, 37, 9007, 1995],
          ['제기동', 471, 14, 5041, 2103]]
df = pd.DataFrame(mydata, columns = ['지하철역', '04-05시 승차인원', '04-05시 하차인원','05-06시 승차인원','05-06시 하차인원'])
df

지하철역  04-05시 승차인원  04-05시 하차인원  05-06시 승차인원  05-06시 하차인원
0  동대문          901           23        11029         1950
1  동묘앞          214            1         2921          933
2  서울역          665           20         7969         7954
3   시청           65            0         2188         4984
4  신설동          373           37         9007         1995
5  제기동          471           14         5041         2103

#### Example 4-1. 승차인원, 하차인원 구하기
우선, 새벽 4시부터 6시까지의 승차인원 열 1개와, 하차인원 열 1개를 만들어서 추가해주세요.

In [9]:
####### PLEASE IMPLEMENT HERE ##########
df['승차인원'] = 
df['하차인원'] = 

In [10]:
df

지하철역  04-05시 승차인원  04-05시 하차인원  05-06시 승차인원  05-06시 하차인원   승차인원  하차인원
0  동대문          901           23        11029         1950  11930  1973
1  동묘앞          214            1         2921          933   3135   934
2  서울역          665           20         7969         7954   8634  7974
3   시청           65            0         2188         4984   2253  4984
4  신설동          373           37         9007         1995   9380  2032
5  제기동          471           14         5041         2103   5512  2117

승차인원이 5000명이 넘는 행들만 골라내주세요.

In [12]:
####### PLEASE IMPLEMENT HERE ##########
result =

In [13]:
result

지하철역  04-05시 승차인원  04-05시 하차인원  05-06시 승차인원  05-06시 하차인원   승차인원  하차인원
0  동대문          901           23        11029         1950  11930  1973
2  서울역          665           20         7969         7954   8634  7974
4  신설동          373           37         9007         1995   9380  2032
5  제기동          471           14         5041         2103   5512  2117