### 연습문제

In [1]:
# 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
A, B = map(int, input().split())
if A > 0 and B<10:
    print(A+B)

In [2]:
# n이 주어졌을 때, n번째 피보나치 수를 구하는 프로그램을 작성하시오.
def fib(n):
    if n == 1 or n == 2:
        return 1
    return  fib(n-1) + fib(n-2)

n = int(input())
if n<=45:
    print(fib(n))

3


### LAB2

In [3]:
st=input()
lst = []
for s in st:
    if s =="a":
        lst.append('000')
    elif s =="b":
        lst.append('001')
    elif s =="c":
        lst.append('010')
    elif s =="d":
        lst.append('011')
    elif s =="e":
        lst.append('100')
print(''.join(lst))

000001010011100


In [1]:
st=input()
lst = [st[(a-1)*3:a*3] for a in range(1, (len(st)//3)+1)]
nlst = []
for s in lst:
    if s =="000":
        nlst.append('a')
    elif s =="001":
        nlst.append('b')
    elif s =="010":
        nlst.append('c')
    elif s =="011":
        nlst.append('d')
    elif s =="100":
        nlst.append('e')
print(''.join(nlst))

abcde


In [2]:
inp = list(map(int, input().split()))
prev = inp[0]
inc = 1
count = 0
for i in range(1, len(inp)):
    if prev < inp[i]:
        inc += 1
    else:
        count = max(count, inc)
        inc = 1
    prev = inp[i]
count = max(count, inc)
print(count)

1


In [3]:
import math

inp = int(input())
count = 0
for j in range(2, inp):
    for i in range(2, math.isqrt(j) + 1):
        if j % i == 0:
            break
    else:
        count += 1
print(count)

8


In [5]:
import numpy as np
pp = int(input())
scores = np.zeros((pp, 10), dtype=int)
for x in range(pp):
    scores[x] = input().split()
print(pp)
print(scores)

3
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [7]:
cheating = np.zeros((pp, 10), dtype=int)
for i in range(pp):
    cheating[i] = list(map(int, input().split()))

for i in range(pp):
    for j in range(10):
        if cheating[i][j] == 1:
            scores[i][j] = 0
print(scores)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [8]:
S = []
l = []
for s in scores:
    if min(s) > 0:
        S.append(sum(s)-min(s))
        l.append(90)
    else:
        S.append(sum(s))
        l.append(90)
n = np.array(S)/np.array(l)*100
print(n)

[0. 0. 0.]


In [10]:
a = open('output.txt', 'w')
a.write('''Coming of age in the 18th and 19th centuries, the personal
diary became a centerpiece in the construction of a modern
subjectivity, at the heart of which is the application of reason
and critique to the understanding of world and self, which
allowed the creation of a new kind of knowledge. Diaries were
central media through which enlightened and free subjects
could be constructed. They provided a space where one could
write daily about her whereabouts, feelings, and thoughts.
Over time and with rereading, disparate entries, events, and
happenstances could be rendered into insights and narratives
about the self, and allowed for the formation of subjectivity. It
is in that context that the idea of “the self [as] both made and
explored with words” emerges. Diaries were personal and
private; one would write for oneself, or, in Habermas’s
formulation, one would make oneself public to oneself. By
making the self public in a private sphere, the self also became
an object for self-inspection and self-critique.''')
a.close()
# exec(input())

In [11]:
import numpy as np

lst = list(map(int, input().split()))

for n in range(1000):
    np.random.seed(n)
    if lst == list(np.random.randint(0, 100, 10)):
        print(n)
        break

In [13]:
s = input()
print('입력된 문자열:', s)
l = s.lower()
u = s.upper()
n = 0
ln, un, b, sp = 0,0,0,0
for i in range(len(l)):
    if s[i] == ' ':
        b += 1
    elif s[i] == l[i] and s[i] not in '.,~!@#$%^&*()_+{}|:"<>?`-=[]\;1234567890':
        ln += 1
    elif s[i] == u[i] and s[i] not in '.,~!@#$%^&*()_+{}|:"<>?`-=[]\;1234567890':
        un += 1
    elif s[i] in '1234567890':
        n += 1
    else:
        sp += 1

print(ln, un, n, b, sp)

입력된 문자열: 123dsafqrE
6 1 3 0 0


In [14]:
import re
def phone(num):
    if re.match(r'^\d{3}-\d{3,4}-\d{4}$', num):
        return '+82-' + num[1:3] + '-' + num[4:8] + '-' + num[9:]
    if re.match(r'^\d{10,11}$', num):
        return '+82-' + num[1:3] + '-' + num[3:7] + '-' + num[7:]
    else :
        return num
n = input()
print(phone(n))

+82-10-3244-9210


In [15]:
import re
import sys
def vemail(email):
    return re.match(r'^[a-zA-Z0-9.]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', email)

def aemail(email, lst):
    lst.append(email[email.find('@')+1:])

lst = []
emails = []
while True:
    email = sys.stdin.readline().rstrip()
    emails.append(email)
    if not email:
        break


for line in emails:
    if line:
        if vemail(line):
            aemail(line, lst)
    else:
        pass
st = set(lst)
for i in lst:
    if i in st:
        print(i,': ', lst.count(i), sep='')
        st.remove(i)

In [ ]:
import re
import sys
def verror(lst):
    f = ''
    en = ''
    for e in lst:
        if re.match(r'^(File)', e):  # Modify the regular expression pattern
            f = e
        elif re.match(r'^(.*?):',e):
            en = e    
    else:
        print('File name:', re.findall(r'\"(.*?)\"', f)[0])  # Print the matched file name
        print('Line number:', re.findall(r'line (\d+)', f)[0])  # Print the matched line number
        print('Error type:', re.findall(r'(.*?):', en)[0])  # Print the matched error type


lst = []
err = []
while True:
    e = sys.stdin.readline().strip()
    err.append(e)
    if not e:
        break

verror(err)


In [1]:
import pandas as pd
s = input()
siz = pd.Series((i for i in s), index=range(1, len(s)+1))
siz[3] = 'datascience'
print(siz)

1              s
2              d
3    datascience
4              s
5              a
6              f
7              2
8              1
dtype: object


In [ ]:
import sys
import pandas as pd
import numpy as np

lst = []
while True:
    ss = sys.stdin.readline().rstrip()
    lst.append(ss)
    if ss == '':
        break
for i, v in enumerate(lst):
    lst[i] = v.split()
del lst[-1]
nlst = np.array(lst)
nlst.T
dic = {'Name':nlst[0],'Age':list(map(int,nlst[1])),'Gender':nlst[2]}
df = pd.DataFrame(dic, columns=['Age', 'Gender'])
df.index = dic['Name']
df.index.name = 'Name'
print(df[df['Age']>=30])

In [ ]:
df = pd.DataFrame(lst).T
df.columns = ['Name','Age', 'Gender']
df['Age'] = df['Age'].apply(int)
df.index = df.pop('Name')
df.index.name = 'Name'
print(df.sort_values('Age', ascending=False))

In [ ]:
df = pd.DataFrame(lst).T
df.columns = ['Name','Age', 'Gender','Occupation']
df['Age'] = df['Age'].apply(int)
df.index = df.pop('Name')
df.index.name = 'Name'
df = df.replace('nodata','Unemployed')
print(df.sort_values('Age', ascending=False))